//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.Presentacion.VS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VS.IVentaService")]
    public interface IVentaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/ListarCategoria", ReplyAction="http://tempuri.org/IVentaService/ListarCategoriaResponse")]
        System.Collections.Generic.List<CarritoCompras.Agente.VS.CategoriaEntidad> ListarCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/ListarCategoria", ReplyAction="http://tempuri.org/IVentaService/ListarCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.CategoriaEntidad>> ListarCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/BuscarProducto", ReplyAction="http://tempuri.org/IVentaService/BuscarProductoResponse")]
        System.Collections.Generic.List<CarritoCompras.Agente.VS.ProductoEntidad> BuscarProducto(CarritoCompras.Agente.VS.ProductoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/BuscarProducto", ReplyAction="http://tempuri.org/IVentaService/BuscarProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.ProductoEntidad>> BuscarProductoAsync(CarritoCompras.Agente.VS.ProductoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/ReservarProducto", ReplyAction="http://tempuri.org/IVentaService/ReservarProductoResponse")]
        CarritoCompras.Agente.VS.ResponseWeb ReservarProducto(CarritoCompras.Agente.VS.ProductoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/ReservarProducto", ReplyAction="http://tempuri.org/IVentaService/ReservarProductoResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Agente.VS.ResponseWeb> ReservarProductoAsync(CarritoCompras.Agente.VS.ProductoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/BuscarDetallePedido", ReplyAction="http://tempuri.org/IVentaService/BuscarDetallePedidoResponse")]
        System.Collections.Generic.List<CarritoCompras.Agente.VS.DetallePedidoEntidad> BuscarDetallePedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/BuscarDetallePedido", ReplyAction="http://tempuri.org/IVentaService/BuscarDetallePedidoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.DetallePedidoEntidad>> BuscarDetallePedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/ListarMediosPago", ReplyAction="http://tempuri.org/IVentaService/ListarMediosPagoResponse")]
        System.Collections.Generic.List<CarritoCompras.Agente.VS.MedioPagoEntidad> ListarMediosPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/ListarMediosPago", ReplyAction="http://tempuri.org/IVentaService/ListarMediosPagoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.MedioPagoEntidad>> ListarMediosPagoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/GrabarVenta", ReplyAction="http://tempuri.org/IVentaService/GrabarVentaResponse")]
        CarritoCompras.Agente.VS.ResponseWeb GrabarVenta(CarritoCompras.Agente.VS.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaService/GrabarVenta", ReplyAction="http://tempuri.org/IVentaService/GrabarVentaResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Agente.VS.ResponseWeb> GrabarVentaAsync(CarritoCompras.Agente.VS.PedidoEntidad entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentaServiceChannel : CarritoCompras.Presentacion.VS.IVentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentaServiceClient : System.ServiceModel.ClientBase<CarritoCompras.Presentacion.VS.IVentaService>, CarritoCompras.Presentacion.VS.IVentaService {
        
        public VentaServiceClient() {
        }
        
        public VentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CarritoCompras.Agente.VS.CategoriaEntidad> ListarCategoria() {
            return base.Channel.ListarCategoria();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.CategoriaEntidad>> ListarCategoriaAsync() {
            return base.Channel.ListarCategoriaAsync();
        }
        
        public System.Collections.Generic.List<CarritoCompras.Agente.VS.ProductoEntidad> BuscarProducto(CarritoCompras.Agente.VS.ProductoEntidad entidad) {
            return base.Channel.BuscarProducto(entidad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.ProductoEntidad>> BuscarProductoAsync(CarritoCompras.Agente.VS.ProductoEntidad entidad) {
            return base.Channel.BuscarProductoAsync(entidad);
        }
        
        public CarritoCompras.Agente.VS.ResponseWeb ReservarProducto(CarritoCompras.Agente.VS.ProductoEntidad entidad) {
            return base.Channel.ReservarProducto(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Agente.VS.ResponseWeb> ReservarProductoAsync(CarritoCompras.Agente.VS.ProductoEntidad entidad) {
            return base.Channel.ReservarProductoAsync(entidad);
        }
        
        public System.Collections.Generic.List<CarritoCompras.Agente.VS.DetallePedidoEntidad> BuscarDetallePedido() {
            return base.Channel.BuscarDetallePedido();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.DetallePedidoEntidad>> BuscarDetallePedidoAsync() {
            return base.Channel.BuscarDetallePedidoAsync();
        }
        
        public System.Collections.Generic.List<CarritoCompras.Agente.VS.MedioPagoEntidad> ListarMediosPago() {
            return base.Channel.ListarMediosPago();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Agente.VS.MedioPagoEntidad>> ListarMediosPagoAsync() {
            return base.Channel.ListarMediosPagoAsync();
        }
        
        public CarritoCompras.Agente.VS.ResponseWeb GrabarVenta(CarritoCompras.Agente.VS.PedidoEntidad entidad) {
            return base.Channel.GrabarVenta(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Agente.VS.ResponseWeb> GrabarVentaAsync(CarritoCompras.Agente.VS.PedidoEntidad entidad) {
            return base.Channel.GrabarVentaAsync(entidad);
        }
    }
}
