//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.Process.CPS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class CategoriaEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_CategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Categoria {
            get {
                return this.Cod_CategoriaField;
            }
            set {
                if ((this.Cod_CategoriaField.Equals(value) != true)) {
                    this.Cod_CategoriaField = value;
                    this.RaisePropertyChanged("Cod_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Categoria {
            get {
                return this.Nom_CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CategoriaField, value) != true)) {
                    this.Nom_CategoriaField = value;
                    this.RaisePropertyChanged("Nom_Categoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CPS.ICategoriaProductoService")]
    public interface ICategoriaProductoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaProductoService/ListarCategoria", ReplyAction="http://tempuri.org/ICategoriaProductoService/ListarCategoriaResponse")]
        System.Collections.Generic.List<CarritoCompras.Process.CPS.CategoriaEntidad> ListarCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaProductoService/ListarCategoria", ReplyAction="http://tempuri.org/ICategoriaProductoService/ListarCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Process.CPS.CategoriaEntidad>> ListarCategoriaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriaProductoServiceChannel : CarritoCompras.Process.CPS.ICategoriaProductoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaProductoServiceClient : System.ServiceModel.ClientBase<CarritoCompras.Process.CPS.ICategoriaProductoService>, CarritoCompras.Process.CPS.ICategoriaProductoService {
        
        public CategoriaProductoServiceClient() {
        }
        
        public CategoriaProductoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaProductoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaProductoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaProductoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CarritoCompras.Process.CPS.CategoriaEntidad> ListarCategoria() {
            return base.Channel.ListarCategoria();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Process.CPS.CategoriaEntidad>> ListarCategoriaAsync() {
            return base.Channel.ListarCategoriaAsync();
        }
    }
}
