//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.Process.PS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class PedidoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarritoCompras.Process.PS.ClienteEntidad ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CarritoCompras.Process.PS.DetallePedidoEntidad> DetallePedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dir_EntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarritoCompras.Process.PS.EstadoPedidoEntidad EstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_EntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarritoCompras.Process.PS.MedioPagoEntidad MedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Total_NetoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarritoCompras.Process.PS.ClienteEntidad Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Pedido {
            get {
                return this.Cod_PedidoField;
            }
            set {
                if ((this.Cod_PedidoField.Equals(value) != true)) {
                    this.Cod_PedidoField = value;
                    this.RaisePropertyChanged("Cod_Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CarritoCompras.Process.PS.DetallePedidoEntidad> DetallePedido {
            get {
                return this.DetallePedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallePedidoField, value) != true)) {
                    this.DetallePedidoField = value;
                    this.RaisePropertyChanged("DetallePedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_Entrega {
            get {
                return this.Dir_EntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.Dir_EntregaField, value) != true)) {
                    this.Dir_EntregaField = value;
                    this.RaisePropertyChanged("Dir_Entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarritoCompras.Process.PS.EstadoPedidoEntidad EstadoPedido {
            get {
                return this.EstadoPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoPedidoField, value) != true)) {
                    this.EstadoPedidoField = value;
                    this.RaisePropertyChanged("EstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Entrega {
            get {
                return this.Fecha_EntregaField;
            }
            set {
                if ((this.Fecha_EntregaField.Equals(value) != true)) {
                    this.Fecha_EntregaField = value;
                    this.RaisePropertyChanged("Fecha_Entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Fin {
            get {
                return this.Fecha_FinField;
            }
            set {
                if ((this.Fecha_FinField.Equals(value) != true)) {
                    this.Fecha_FinField = value;
                    this.RaisePropertyChanged("Fecha_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Inicio {
            get {
                return this.Fecha_InicioField;
            }
            set {
                if ((this.Fecha_InicioField.Equals(value) != true)) {
                    this.Fecha_InicioField = value;
                    this.RaisePropertyChanged("Fecha_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Pedido {
            get {
                return this.Fecha_PedidoField;
            }
            set {
                if ((this.Fecha_PedidoField.Equals(value) != true)) {
                    this.Fecha_PedidoField = value;
                    this.RaisePropertyChanged("Fecha_Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarritoCompras.Process.PS.MedioPagoEntidad MedioPago {
            get {
                return this.MedioPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedioPagoField, value) != true)) {
                    this.MedioPagoField = value;
                    this.RaisePropertyChanged("MedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Pedido {
            get {
                return this.Num_PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_PedidoField, value) != true)) {
                    this.Num_PedidoField = value;
                    this.RaisePropertyChanged("Num_Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total_Neto {
            get {
                return this.Total_NetoField;
            }
            set {
                if ((this.Total_NetoField.Equals(value) != true)) {
                    this.Total_NetoField = value;
                    this.RaisePropertyChanged("Total_Neto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class ClienteEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ema_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Cliente {
            get {
                return this.Cod_ClienteField;
            }
            set {
                if ((this.Cod_ClienteField.Equals(value) != true)) {
                    this.Cod_ClienteField = value;
                    this.RaisePropertyChanged("Cod_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ema_Cliente {
            get {
                return this.Ema_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Ema_ClienteField, value) != true)) {
                    this.Ema_ClienteField = value;
                    this.RaisePropertyChanged("Ema_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Cliente {
            get {
                return this.Nom_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ClienteField, value) != true)) {
                    this.Nom_ClienteField = value;
                    this.RaisePropertyChanged("Nom_Cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPedidoEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class EstadoPedidoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_EstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_EstadoPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_EstadoPedido {
            get {
                return this.Cod_EstadoPedidoField;
            }
            set {
                if ((this.Cod_EstadoPedidoField.Equals(value) != true)) {
                    this.Cod_EstadoPedidoField = value;
                    this.RaisePropertyChanged("Cod_EstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_EstadoPedido {
            get {
                return this.Nom_EstadoPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_EstadoPedidoField, value) != true)) {
                    this.Nom_EstadoPedidoField = value;
                    this.RaisePropertyChanged("Nom_EstadoPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedioPagoEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class MedioPagoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_MedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_MedioPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_MedioPago {
            get {
                return this.Cod_MedioPagoField;
            }
            set {
                if ((this.Cod_MedioPagoField.Equals(value) != true)) {
                    this.Cod_MedioPagoField = value;
                    this.RaisePropertyChanged("Cod_MedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_MedioPago {
            get {
                return this.Nom_MedioPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_MedioPagoField, value) != true)) {
                    this.Nom_MedioPagoField = value;
                    this.RaisePropertyChanged("Nom_MedioPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePedidoEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class DetallePedidoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_DetallePedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarritoCompras.Process.PS.ProductoEntidad ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_DetallePedido {
            get {
                return this.Cod_DetallePedidoField;
            }
            set {
                if ((this.Cod_DetallePedidoField.Equals(value) != true)) {
                    this.Cod_DetallePedidoField = value;
                    this.RaisePropertyChanged("Cod_DetallePedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Pedido {
            get {
                return this.Cod_PedidoField;
            }
            set {
                if ((this.Cod_PedidoField.Equals(value) != true)) {
                    this.Cod_PedidoField = value;
                    this.RaisePropertyChanged("Cod_Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarritoCompras.Process.PS.ProductoEntidad Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class ProductoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarritoCompras.Process.PS.CategoriaEntidad CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarritoCompras.Process.PS.UnidadMedidaEntidad UnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarritoCompras.Process.PS.CategoriaEntidad Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Producto {
            get {
                return this.Cod_ProductoField;
            }
            set {
                if ((this.Cod_ProductoField.Equals(value) != true)) {
                    this.Cod_ProductoField = value;
                    this.RaisePropertyChanged("Cod_Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Producto {
            get {
                return this.Nom_ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ProductoField, value) != true)) {
                    this.Nom_ProductoField = value;
                    this.RaisePropertyChanged("Nom_Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarritoCompras.Process.PS.UnidadMedidaEntidad UnidadMedida {
            get {
                return this.UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadMedidaField, value) != true)) {
                    this.UnidadMedidaField = value;
                    this.RaisePropertyChanged("UnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class CategoriaEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_CategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Categoria {
            get {
                return this.Cod_CategoriaField;
            }
            set {
                if ((this.Cod_CategoriaField.Equals(value) != true)) {
                    this.Cod_CategoriaField = value;
                    this.RaisePropertyChanged("Cod_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Categoria {
            get {
                return this.Nom_CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CategoriaField, value) != true)) {
                    this.Nom_CategoriaField = value;
                    this.RaisePropertyChanged("Nom_Categoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadMedidaEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class UnidadMedidaEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_UnidadMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_UnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_UnidadMedida {
            get {
                return this.Cod_UnidadMedidaField;
            }
            set {
                if ((this.Cod_UnidadMedidaField.Equals(value) != true)) {
                    this.Cod_UnidadMedidaField = value;
                    this.RaisePropertyChanged("Cod_UnidadMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_UnidadMedida {
            get {
                return this.Nom_UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_UnidadMedidaField, value) != true)) {
                    this.Nom_UnidadMedidaField = value;
                    this.RaisePropertyChanged("Nom_UnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWeb", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Utilitario")]
    [System.SerializableAttribute()]
    public partial class ResponseWeb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PS.IPedidoService")]
    public interface IPedidoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/GuardarPedido", ReplyAction="http://tempuri.org/IPedidoService/GuardarPedidoResponse")]
        CarritoCompras.Process.PS.ResponseWeb GuardarPedido(CarritoCompras.Process.PS.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/GuardarPedido", ReplyAction="http://tempuri.org/IPedidoService/GuardarPedidoResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Process.PS.ResponseWeb> GuardarPedidoAsync(CarritoCompras.Process.PS.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ConsultarPedido", ReplyAction="http://tempuri.org/IPedidoService/ConsultarPedidoResponse")]
        System.Collections.Generic.List<CarritoCompras.Process.PS.PedidoEntidad> ConsultarPedido(CarritoCompras.Process.PS.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ConsultarPedido", ReplyAction="http://tempuri.org/IPedidoService/ConsultarPedidoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Process.PS.PedidoEntidad>> ConsultarPedidoAsync(CarritoCompras.Process.PS.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ModificarPedido", ReplyAction="http://tempuri.org/IPedidoService/ModificarPedidoResponse")]
        CarritoCompras.Process.PS.ResponseWeb ModificarPedido(CarritoCompras.Process.PS.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ModificarPedido", ReplyAction="http://tempuri.org/IPedidoService/ModificarPedidoResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Process.PS.ResponseWeb> ModificarPedidoAsync(CarritoCompras.Process.PS.PedidoEntidad entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoServiceChannel : CarritoCompras.Process.PS.IPedidoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoServiceClient : System.ServiceModel.ClientBase<CarritoCompras.Process.PS.IPedidoService>, CarritoCompras.Process.PS.IPedidoService {
        
        public PedidoServiceClient() {
        }
        
        public PedidoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarritoCompras.Process.PS.ResponseWeb GuardarPedido(CarritoCompras.Process.PS.PedidoEntidad entidad) {
            return base.Channel.GuardarPedido(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Process.PS.ResponseWeb> GuardarPedidoAsync(CarritoCompras.Process.PS.PedidoEntidad entidad) {
            return base.Channel.GuardarPedidoAsync(entidad);
        }
        
        public System.Collections.Generic.List<CarritoCompras.Process.PS.PedidoEntidad> ConsultarPedido(CarritoCompras.Process.PS.PedidoEntidad entidad) {
            return base.Channel.ConsultarPedido(entidad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Process.PS.PedidoEntidad>> ConsultarPedidoAsync(CarritoCompras.Process.PS.PedidoEntidad entidad) {
            return base.Channel.ConsultarPedidoAsync(entidad);
        }
        
        public CarritoCompras.Process.PS.ResponseWeb ModificarPedido(CarritoCompras.Process.PS.PedidoEntidad entidad) {
            return base.Channel.ModificarPedido(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Process.PS.ResponseWeb> ModificarPedidoAsync(CarritoCompras.Process.PS.PedidoEntidad entidad) {
            return base.Channel.ModificarPedidoAsync(entidad);
        }
    }
}
