//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.Agente.US {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class UsuarioEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pass_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Perfil_UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Usuario {
            get {
                return this.Cod_UsuarioField;
            }
            set {
                if ((this.Cod_UsuarioField.Equals(value) != true)) {
                    this.Cod_UsuarioField = value;
                    this.RaisePropertyChanged("Cod_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Usuario {
            get {
                return this.Nom_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_UsuarioField, value) != true)) {
                    this.Nom_UsuarioField = value;
                    this.RaisePropertyChanged("Nom_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass_Usuario {
            get {
                return this.Pass_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Pass_UsuarioField, value) != true)) {
                    this.Pass_UsuarioField = value;
                    this.RaisePropertyChanged("Pass_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil_Usuario {
            get {
                return this.Perfil_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Perfil_UsuarioField, value) != true)) {
                    this.Perfil_UsuarioField = value;
                    this.RaisePropertyChanged("Perfil_Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="US.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ValidarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ValidarUsuarioResponse")]
        CarritoCompras.Agente.US.UsuarioEntidad ValidarUsuario(CarritoCompras.Agente.US.UsuarioEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ValidarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Agente.US.UsuarioEntidad> ValidarUsuarioAsync(CarritoCompras.Agente.US.UsuarioEntidad entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : CarritoCompras.Agente.US.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<CarritoCompras.Agente.US.IUsuarioService>, CarritoCompras.Agente.US.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarritoCompras.Agente.US.UsuarioEntidad ValidarUsuario(CarritoCompras.Agente.US.UsuarioEntidad entidad) {
            return base.Channel.ValidarUsuario(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Agente.US.UsuarioEntidad> ValidarUsuarioAsync(CarritoCompras.Agente.US.UsuarioEntidad entidad) {
            return base.Channel.ValidarUsuarioAsync(entidad);
        }
    }
}
