//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.Process.CLIS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteEntidad", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Entidad")]
    [System.SerializableAttribute()]
    public partial class ClienteEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ema_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Cliente {
            get {
                return this.Cod_ClienteField;
            }
            set {
                if ((this.Cod_ClienteField.Equals(value) != true)) {
                    this.Cod_ClienteField = value;
                    this.RaisePropertyChanged("Cod_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ema_Cliente {
            get {
                return this.Ema_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Ema_ClienteField, value) != true)) {
                    this.Ema_ClienteField = value;
                    this.RaisePropertyChanged("Ema_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Cliente {
            get {
                return this.Nom_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ClienteField, value) != true)) {
                    this.Nom_ClienteField = value;
                    this.RaisePropertyChanged("Nom_Cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWeb", Namespace="http://schemas.datacontract.org/2004/07/CarritoCompras.Utilitario")]
    [System.SerializableAttribute()]
    public partial class ResponseWeb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CLIS.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GuardarCliente", ReplyAction="http://tempuri.org/IClienteService/GuardarClienteResponse")]
        CarritoCompras.Process.CLIS.ResponseWeb GuardarCliente(CarritoCompras.Process.CLIS.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GuardarCliente", ReplyAction="http://tempuri.org/IClienteService/GuardarClienteResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Process.CLIS.ResponseWeb> GuardarClienteAsync(CarritoCompras.Process.CLIS.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ActualizarCliente", ReplyAction="http://tempuri.org/IClienteService/ActualizarClienteResponse")]
        CarritoCompras.Process.CLIS.ResponseWeb ActualizarCliente(CarritoCompras.Process.CLIS.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ActualizarCliente", ReplyAction="http://tempuri.org/IClienteService/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Process.CLIS.ResponseWeb> ActualizarClienteAsync(CarritoCompras.Process.CLIS.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/BuscarCliente", ReplyAction="http://tempuri.org/IClienteService/BuscarClienteResponse")]
        CarritoCompras.Process.CLIS.ClienteEntidad BuscarCliente(CarritoCompras.Process.CLIS.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/BuscarCliente", ReplyAction="http://tempuri.org/IClienteService/BuscarClienteResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Process.CLIS.ClienteEntidad> BuscarClienteAsync(CarritoCompras.Process.CLIS.ClienteEntidad entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : CarritoCompras.Process.CLIS.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<CarritoCompras.Process.CLIS.IClienteService>, CarritoCompras.Process.CLIS.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarritoCompras.Process.CLIS.ResponseWeb GuardarCliente(CarritoCompras.Process.CLIS.ClienteEntidad entidad) {
            return base.Channel.GuardarCliente(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Process.CLIS.ResponseWeb> GuardarClienteAsync(CarritoCompras.Process.CLIS.ClienteEntidad entidad) {
            return base.Channel.GuardarClienteAsync(entidad);
        }
        
        public CarritoCompras.Process.CLIS.ResponseWeb ActualizarCliente(CarritoCompras.Process.CLIS.ClienteEntidad entidad) {
            return base.Channel.ActualizarCliente(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Process.CLIS.ResponseWeb> ActualizarClienteAsync(CarritoCompras.Process.CLIS.ClienteEntidad entidad) {
            return base.Channel.ActualizarClienteAsync(entidad);
        }
        
        public CarritoCompras.Process.CLIS.ClienteEntidad BuscarCliente(CarritoCompras.Process.CLIS.ClienteEntidad entidad) {
            return base.Channel.BuscarCliente(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Process.CLIS.ClienteEntidad> BuscarClienteAsync(CarritoCompras.Process.CLIS.ClienteEntidad entidad) {
            return base.Channel.BuscarClienteAsync(entidad);
        }
    }
}
