//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.EntityService.MCS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MCS.IMacroConsultaService")]
    public interface IMacroConsultaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerCategorias", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerCategoriasResponse")]
        System.Collections.Generic.List<CarritoCompras.Entidad.CategoriaEntidad> ObtenerCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerCategorias", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerCategoriasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.CategoriaEntidad>> ObtenerCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerMediosPago", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerMediosPagoResponse")]
        System.Collections.Generic.List<CarritoCompras.Entidad.MedioPagoEntidad> ObtenerMediosPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerMediosPago", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerMediosPagoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.MedioPagoEntidad>> ObtenerMediosPagoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerProductos", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerProductosResponse")]
        System.Collections.Generic.List<CarritoCompras.Entidad.ProductoEntidad> ObtenerProductos(CarritoCompras.Entidad.ProductoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerProductos", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerProductosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.ProductoEntidad>> ObtenerProductosAsync(CarritoCompras.Entidad.ProductoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerCliente", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerClienteResponse")]
        CarritoCompras.Entidad.ClienteEntidad ObtenerCliente(CarritoCompras.Entidad.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerCliente", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<CarritoCompras.Entidad.ClienteEntidad> ObtenerClienteAsync(CarritoCompras.Entidad.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerPedido", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerPedidoResponse")]
        System.Collections.Generic.List<CarritoCompras.Entidad.PedidoEntidad> ObtenerPedido(CarritoCompras.Entidad.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerPedido", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerPedidoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.PedidoEntidad>> ObtenerPedidoAsync(CarritoCompras.Entidad.PedidoEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerDetallePedido", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerDetallePedidoResponse")]
        System.Collections.Generic.List<CarritoCompras.Entidad.DetallePedidoEntidad> ObtenerDetallePedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMacroConsultaService/ObtenerDetallePedido", ReplyAction="http://tempuri.org/IMacroConsultaService/ObtenerDetallePedidoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.DetallePedidoEntidad>> ObtenerDetallePedidoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMacroConsultaServiceChannel : CarritoCompras.EntityService.MCS.IMacroConsultaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MacroConsultaServiceClient : System.ServiceModel.ClientBase<CarritoCompras.EntityService.MCS.IMacroConsultaService>, CarritoCompras.EntityService.MCS.IMacroConsultaService {
        
        public MacroConsultaServiceClient() {
        }
        
        public MacroConsultaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MacroConsultaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MacroConsultaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MacroConsultaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CarritoCompras.Entidad.CategoriaEntidad> ObtenerCategorias() {
            return base.Channel.ObtenerCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.CategoriaEntidad>> ObtenerCategoriasAsync() {
            return base.Channel.ObtenerCategoriasAsync();
        }
        
        public System.Collections.Generic.List<CarritoCompras.Entidad.MedioPagoEntidad> ObtenerMediosPago() {
            return base.Channel.ObtenerMediosPago();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.MedioPagoEntidad>> ObtenerMediosPagoAsync() {
            return base.Channel.ObtenerMediosPagoAsync();
        }
        
        public System.Collections.Generic.List<CarritoCompras.Entidad.ProductoEntidad> ObtenerProductos(CarritoCompras.Entidad.ProductoEntidad entidad) {
            return base.Channel.ObtenerProductos(entidad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.ProductoEntidad>> ObtenerProductosAsync(CarritoCompras.Entidad.ProductoEntidad entidad) {
            return base.Channel.ObtenerProductosAsync(entidad);
        }
        
        public CarritoCompras.Entidad.ClienteEntidad ObtenerCliente(CarritoCompras.Entidad.ClienteEntidad entidad) {
            return base.Channel.ObtenerCliente(entidad);
        }
        
        public System.Threading.Tasks.Task<CarritoCompras.Entidad.ClienteEntidad> ObtenerClienteAsync(CarritoCompras.Entidad.ClienteEntidad entidad) {
            return base.Channel.ObtenerClienteAsync(entidad);
        }
        
        public System.Collections.Generic.List<CarritoCompras.Entidad.PedidoEntidad> ObtenerPedido(CarritoCompras.Entidad.PedidoEntidad entidad) {
            return base.Channel.ObtenerPedido(entidad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.PedidoEntidad>> ObtenerPedidoAsync(CarritoCompras.Entidad.PedidoEntidad entidad) {
            return base.Channel.ObtenerPedidoAsync(entidad);
        }
        
        public System.Collections.Generic.List<CarritoCompras.Entidad.DetallePedidoEntidad> ObtenerDetallePedido() {
            return base.Channel.ObtenerDetallePedido();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CarritoCompras.Entidad.DetallePedidoEntidad>> ObtenerDetallePedidoAsync() {
            return base.Channel.ObtenerDetallePedidoAsync();
        }
    }
}
